# Generated by Django 4.0.4 on 2022-04-13 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Average',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_value', models.FloatField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_value', models.FloatField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_firstname', models.CharField(max_length=200)),
                ('student_lastname', models.CharField(max_length=200)),
                ('student_birth', models.DateTimeField(verbose_name='birth_date')),
                ('student_average', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.average')),
                ('student_classes', models.ManyToManyField(to='profil.classes')),
                ('student_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.images')),
                ('student_notes', models.ManyToManyField(to='profil.notes')),
                ('student_promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.promotion')),
            ],
        ),
    ]
