# Generated by Django 4.0.4 on 2022-04-13 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_birth',
        ),
    ]
