# Generated by Django 4.0.4 on 2022-04-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_remove_student_student_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_image',
            field=models.ImageField(blank=True, null=True, upload_to='../img'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
